### ISSUE TITLE
`CloudResponse` is unusable

### ISSUE THREAD

**Issue by syrull** [bitmartexchange/bitmart-go-sdk-api#1]
Hello I am trying to use the SDK, but for an example I want to see if the status code of the request that I've made is `200`, how do I do that when the struct for the `CloudResponse` looks like so:

```go
type CloudResponse struct {
	httpStatus int
	response   string
	limit      RateLimit
}
```

Basically the `response` object is being unusable since that the fields are not exported, how can I make use of that or do I understand that wrong?

**Comment by alexjorgef** [comment]
I'd wonder the same thing. I don't know if this is SDK's desired behavior, but these fields should be exported, right?
Btw, we can extract unexported fields from structs with `reflect` std package:

```go
import (
	"reflect"

	"github.com/bitmartexchange/bitmart-go-sdk-api"
)

func main() {
	client := bitmart.NewClient(bitmart.Config{
		Url:           "https://api-cloud.bitmart.com",
		ApiKey:        "Your API KEY",
		SecretKey:     "Your Secret KEY",
		Memo:          "Your Memo",
		TimeoutSecond: 10,
		IsPrint:       false,
	})

	symbols, err := client.GetSpotSymbol()
	if err != nil {
		// Handle error
	}

	// Extract string response field from CloudResponse struct
	v := reflect.ValueOf(*symbols)
	res := v.FieldByName("response")

	fmt.Printf("%T %v\n", res.String(), res.String())
}
```

**Comment by 11101171** [comment]
ok, we will consider adding this feature to the SDK. Thanks for the suggestion.
