### ISSUE TITLE
ws Dial失败时有可能会导致程序直接中断了

### ISSUE THREAD

**Issue by wang0402** [bitmartexchange/bitmart-go-sdk-api#3]
// reconnect to websocket
func (ws *CloudWS) reconnection() {
	time.Sleep(time.Duration(2) * time.Second)

	log.Printf("Reconnecting to %s", ws.Config.WsUrl)
	c, _, err := websocket.DefaultDialer.Dial(ws.Config.WsUrl, nil)

	if err != nil {
		log.Fatalf("Connect failed. dial:%+v", err)
	}

	if ws.Config.IsPrint {
		log.Printf("Connected to %s", ws.Config.WsUrl)
	}

	ws.Conn = c
	if ws.reconnectUseLogin {
		ws.SubscribeWithLogin(ws.reconnectUseChannels)
	} else {
		ws.SubscribeWithoutLogin(ws.reconnectUseChannels)
	}
 
}
这里的log.Fatalf 会引发此问题

**Comment by 11101171** [comment]
好的，我们会检查一下，谢谢你的反馈！
